// Estilos compartilhados entre /login e /criar — visual único (tipo Resend):
// card enxuto, uma única ação por tela, sem abas.
export const s = {
  root: {
    minHeight: '100vh',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'radial-gradient(circle at top, #2C1422 0%, var(--brand-dark-bg, #170D14) 100%)',
    padding: 20,
    overflowY: 'auto',
  },
  card: {
    background: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 24,
    padding: '28px 28px 20px',
    margin: 'auto',
    border: '1px solid rgba(255, 255, 255, 0.07)',
    boxShadow: '0 24px 64px rgba(0, 0, 0, 0.45), inset 0 1px 0 rgba(255, 255, 255, 0.1)',
    backdropFilter: 'blur(20px)',
    WebkitBackdropFilter: 'blur(20px)',
  },
  voltar: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 3,
    fontSize: 12,
    color: 'rgba(255,255,255,0.5)',
    textDecoration: 'none',
    marginBottom: 18,
  },
  title: {
    fontSize: 19,
    fontWeight: 700,
    color: '#fff',
    margin: '0 0 4px',
    fontFamily: "'Bricolage Grotesque', sans-serif",
  },
  subtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.5)',
    margin: '0 0 20px',
  },
  switchTop: {
    textAlign: 'center',
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.55)',
    margin: '4px 0 20px',
  },
  googleCircle: {
    width: 44,
    height: 44,
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.06)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  googleTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: '#fff',
    margin: 0,
  },
  googleText: {
    fontSize: 12.5,
    color: 'rgba(255,255,255,0.5)',
    lineHeight: 1.5,
    margin: 0,
    maxWidth: 230,
  },
  btnGoogle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    width: '100%',
    background: '#fff',
    color: '#3c4043',
    border: '1px solid rgba(0,0,0,0.1)',
    borderRadius: 'var(--radius-sm)',
    padding: '11px 0',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: "'Bricolage Grotesque', sans-serif",
  },
  consentGoogle: {
    fontSize: 11.5,
    color: 'rgba(255,255,255,0.55)',
    lineHeight: 1.4,
    textAlign: 'center',
    margin: '8px 0 0',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    margin: '18px 0',
  },
  dividerLine: {
    flex: 1,
    height: 1,
    background: 'rgba(255,255,255,0.12)',
  },
  dividerText: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.5)',
  },
  form: { display: 'flex', flexDirection: 'column', gap: 10 },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: 'rgba(255, 255, 255, 0.85)',
    letterSpacing: '0.3px'
  },
  input: {
    padding: '10px 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    fontSize: 14,
    color: '#FFFFFF',
    background: 'rgba(255, 255, 255, 0.04)',
    outline: 'none',
    transition: 'all 0.22s ease',
  },
  error: {
    background: 'rgba(185, 28, 28, 0.15)',
    color: '#FF8A8A',
    fontSize: 13,
    padding: '10px 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid rgba(185, 28, 28, 0.3)',
    fontWeight: 500
  },
  success: {
    background: 'rgba(21, 128, 61, 0.18)',
    color: '#86EFAC',
    fontSize: 13,
    padding: '10px 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid rgba(21,128,61,0.35)',
    fontWeight: 500,
    lineHeight: 1.5,
  },
  recuperarTexto: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.7)',
    lineHeight: 1.55,
    margin: '0 0 2px',
  },
  esqueciBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--gold, #E6C260)',
    fontSize: 12.5,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    alignSelf: 'flex-end',
    padding: 0,
    marginTop: -4,
  },
  linkBtn: {
    background: 'transparent',
    border: 'none',
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginTop: 2,
  },
  btn: {
    background: 'var(--gold, #E6C260)',
    color: 'var(--brand-dark-bg, #170D14)',
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    padding: '12px 0',
    fontSize: 14,
    fontWeight: 800,
    cursor: 'pointer',
    marginTop: 2,
    boxShadow: 'var(--shadow-gold)',
    transition: 'all 0.2s ease',
    fontFamily: "'Bricolage Grotesque', sans-serif",
  },
  termosRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
    fontSize: 12,
    color: 'rgba(255,255,255,0.75)',
    cursor: 'pointer',
    lineHeight: 1.4,
    padding: '2px 0',
  },
  checkbox: {
    width: 16,
    height: 16,
    marginTop: 2,
    cursor: 'pointer',
    accentColor: 'var(--gold, #E6C260)',
    flexShrink: 0,
  },
  linkTermos: {
    color: 'var(--gold, #E6C260)',
    textDecoration: 'underline',
    fontWeight: 600,
  },
  switchRow: {
    textAlign: 'center',
    marginTop: 18,
    fontSize: 13,
    color: 'rgba(255,255,255,0.55)',
  },
  switchLink: {
    color: 'var(--gold, #E6C260)',
    textDecoration: 'none',
    fontWeight: 700,
  },
  footer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 14,
    fontSize: 12,
  },
  footerLink: {
    color: 'rgba(255,255,255,0.5)',
    textDecoration: 'none',
    fontWeight: 500,
  },
}
