import { inputBase, btnPrimaryBase, btnSecondaryBase } from '../lib/ui'

// Estilos da tela de Agenda (separados do componente para deixar a lógica mais enxuta).
export const s = {
  page: { padding: 16, paddingBottom: 80, overflowX: 'hidden' },
  sectionTitle: { fontSize: 12, fontWeight: 600, color: 'var(--text2)', textTransform: 'capitalize', margin: '0 0 8px', display: 'flex', alignItems: 'center', gap: 6 },
  hojeChip: { fontSize: 10, background: 'var(--pink)', color: 'white', borderRadius: 20, padding: '2px 9px', fontWeight: 700 },
  viewTabs: { display: 'flex', background: 'var(--surface)', borderRadius: 'var(--radius-sm)', padding: 3, marginBottom: 12, gap: 3, boxShadow: 'var(--shadow-xs)', border: '1px solid var(--border)' },
  viewTab: { flex: 1, padding: '8px 0', borderRadius: 7, fontSize: 13, fontWeight: 500, background: 'transparent', color: 'var(--text3)', border: 'none', cursor: 'pointer', transition: 'all 0.15s' },
  viewTabActive: { background: 'white', color: 'var(--pink)', boxShadow: 'var(--shadow-xs)', fontWeight: 700 },
  nav: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '10px 14px', boxShadow: 'var(--shadow-xs)' },
  buscaWrap: { display: 'flex', alignItems: 'center', gap: 8, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '9px 12px', marginBottom: 12, boxShadow: 'var(--shadow-xs)' },
  buscaInput: { flex: 1, border: 'none', outline: 'none', background: 'transparent', fontSize: 14, color: 'var(--text)', fontFamily: 'inherit' },
  buscaClear: { background: 'var(--surface2)', border: 'none', borderRadius: '50%', width: 24, height: 24, display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', color: 'var(--text2)', flexShrink: 0 },
  buscaResumo: { fontSize: 11, fontWeight: 700, color: 'var(--text3)', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 10 },
  cardDataBusca: { display: 'flex', flexDirection: 'column', alignItems: 'center', minWidth: 44, background: 'var(--surface2)', borderRadius: 7, padding: '4px 6px' },
  cardDataBuscaDia: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12, fontWeight: 700, color: 'var(--text)' },
  cardDataBuscaHora: { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, color: 'var(--text3)', marginTop: 1 },
  profFiltro: { display: 'flex', gap: 6, overflowX: 'auto', marginBottom: 14, paddingBottom: 2 },
  profChip: { flexShrink: 0, padding: '6px 14px', borderRadius: 'var(--radius-pill)', fontSize: 12.5, fontWeight: 600, background: 'var(--surface)', color: 'var(--text2)', border: '1px solid var(--border)', cursor: 'pointer', whiteSpace: 'nowrap' },
  profChipAtivo: { background: 'var(--pink)', color: 'white', borderColor: 'var(--pink)' },
  navBtn: { background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text2)', display: 'flex', alignItems: 'center', padding: 4 },
  navLabel: { fontFamily: "'Bricolage Grotesque', sans-serif", fontSize: 14, fontWeight: 700, color: 'var(--text)', textTransform: 'capitalize' },
  weekGrid: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 4, marginBottom: 4 },
  weekDay: { display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '6px 2px', borderRadius: 9, cursor: 'pointer', background: 'var(--surface2)', border: '1px solid var(--border)' },
  weekDayHoje: { background: 'var(--pink-light)', border: '1px solid var(--pink-mid)' },
  weekDayLabel: { fontSize: 10, color: 'var(--text3)', fontWeight: 600, textTransform: 'uppercase' },
  weekDayNum: { fontFamily: "'JetBrains Mono', monospace", fontSize: 15, fontWeight: 500, color: 'var(--text)', margin: '2px 0' },
  weekDayNumHoje: { color: 'var(--pink)' },
  weekDots: { display: 'flex', gap: 2, alignItems: 'center', flexWrap: 'wrap', justifyContent: 'center' },
  weekDot: { width: 5, height: 5, borderRadius: '50%' },
  calHeader: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', marginBottom: 2 },
  calHeaderCell: { fontSize: 10, fontWeight: 700, color: 'var(--text3)', textAlign: 'center', padding: '4px 0', textTransform: 'uppercase' },
  calRow: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 1, marginBottom: 1 },
  calCell: { minHeight: 54, padding: '3px 4px', background: 'var(--surface)', border: '1px solid var(--border)', cursor: 'pointer', borderRadius: 5 },
  calCellOut: { background: 'var(--surface2)', opacity: 0.5 },
  calCellHoje: { background: 'var(--pink-light)', border: '1px solid var(--pink-mid)' },
  calCellSel: { background: 'var(--pink-light)', border: '2px solid var(--pink)', outline: '2px solid var(--pink-mid)' },
  calNum: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12, fontWeight: 500, color: 'var(--text)', marginBottom: 2 },
  calNumHoje: { color: 'var(--pink)', fontWeight: 700 },
  calEvent: { fontSize: 9, borderRadius: 3, padding: '1px 4px', marginBottom: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: '100%', display: 'block' },
  calMore: { fontSize: 9, color: 'var(--text3)' },
  card: { background: 'var(--surface)', border: '1px solid var(--border)', borderLeft: '4px solid var(--pink)', borderRadius: 'var(--radius-sm)', padding: '13px 14px', marginBottom: 10, boxShadow: 'var(--shadow-sm)', position: 'relative' },
  cardHeader: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 },
  cardTime: { fontFamily: "'JetBrains Mono', monospace", fontSize: 14, fontWeight: 500, color: 'var(--text)', minWidth: 44, background: 'var(--surface2)', borderRadius: 7, padding: '3px 7px', textAlign: 'center' },
  cardName: { fontSize: 14, fontWeight: 700 },
  cardService: { fontSize: 12, color: 'var(--text3)', marginTop: 1 },
  cardValor: { fontFamily: "'JetBrains Mono', monospace", fontSize: 14, fontWeight: 500, color: 'var(--pink)' },
  actionBtn: { display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, fontWeight: 600, padding: '4px 10px', borderRadius: 'var(--radius-pill)', border: 'none', cursor: 'pointer', transition: 'opacity 0.15s', fontFamily: 'inherit' },
  badge: { fontSize: 11, padding: '3px 10px', borderRadius: 'var(--radius-pill)', fontWeight: 600, whiteSpace: 'nowrap' },
  /* Menu 3 pontos */
  menuBtn: { width: 30, height: 30, borderRadius: '50%', border: '1px solid var(--border)', background: 'var(--surface2)', color: 'var(--text2)', fontSize: 16, fontWeight: 700, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', letterSpacing: 1, flexShrink: 0 },
  menu: { position: 'absolute', top: 46, right: 12, background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', boxShadow: 'var(--shadow-md)', zIndex: 50, minWidth: 200, overflow: 'hidden' },
  menuItem: { display: 'block', width: '100%', padding: '10px 14px', fontSize: 13, fontWeight: 500, textAlign: 'left', background: 'none', border: 'none', borderBottom: '1px solid var(--border)', cursor: 'pointer', color: 'var(--text)', textDecoration: 'none', fontFamily: 'inherit' },
  /* Semana colunas */
  weekColunas: { display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 6, marginTop: 10, overflowX: 'auto' },
  weekColuna: { minWidth: 110, display: 'flex', flexDirection: 'column', gap: 4 },
  weekColunaHeader: { display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '6px 4px', borderRadius: 8, background: 'var(--surface2)', border: '1px solid var(--border)', cursor: 'pointer', marginBottom: 2 },
  weekColunaHeaderHoje: { background: 'var(--pink-light)', border: '1px solid var(--pink-mid)' },
  weekColunaDia: { fontSize: 10, fontWeight: 600, color: 'var(--text3)', textTransform: 'uppercase' },
  weekColunaNum: { fontFamily: "'JetBrains Mono', monospace", fontSize: 16, fontWeight: 500, color: 'var(--text)' },
  weekColunaSemAg: { fontSize: 12, color: 'var(--border2)', textAlign: 'center', padding: '10px 0' },
  /* Card compacto (view semana) */
  cardCompacto: { display: 'flex', alignItems: 'center', gap: 5, background: 'var(--surface)', border: '1px solid var(--border)', borderLeft: '3px solid', borderRadius: 6, padding: '6px 7px', cursor: 'pointer', position: 'relative' },
  cardCompactoHora: { fontFamily: "'JetBrains Mono', monospace", fontSize: 10, fontWeight: 600, color: 'var(--text2)', whiteSpace: 'nowrap' },
  cardCompactoNome: { fontSize: 11, fontWeight: 700, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  cardCompactoServ: { fontSize: 10, color: 'var(--text3)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  empty: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '40px 20px', textAlign: 'center' },
  emptyBtn: { marginTop: 14, background: 'var(--pink)', color: 'white', border: 'none', borderRadius: 'var(--radius-sm)', padding: '11px 22px', fontSize: 13, fontWeight: 600, cursor: 'pointer', boxShadow: 'var(--shadow-pink)' },
  modal: { background: 'var(--surface)', borderRadius: 18, padding: '18px 16px 20px', width: '100%', maxWidth: 480, display: 'flex', flexDirection: 'column', gap: 10, maxHeight: '92vh', overflowY: 'auto' },
  modalTitle: { fontSize: 17, fontWeight: 700, marginBottom: 2 },
  pagInfo: { background: 'var(--surface2)', borderRadius: 'var(--radius-sm)', padding: '11px 14px', border: '1px solid var(--border)' },
  pagCliente: { fontSize: 14, fontWeight: 700 },
  pagServico: { fontSize: 12, color: 'var(--text3)', marginTop: 3 },
  formasGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 9, marginTop: 4 },
  formaBtn: { padding: '11px 8px', borderRadius: 'var(--radius-sm)', border: '1.5px solid var(--border2)', background: 'var(--surface)', fontSize: 13, fontWeight: 500, cursor: 'pointer', textAlign: 'center', color: 'var(--text2)', transition: 'all 0.15s' },
  formaBtnActive: { border: '1.5px solid var(--pink)', background: 'var(--pink-light)', color: 'var(--pink)', fontWeight: 700 },
  statusGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 9, marginTop: 4 },
  statusBtn2: { padding: '11px 8px', borderRadius: 'var(--radius-sm)', border: '1.5px solid var(--border2)', background: 'var(--surface)', fontSize: 13, fontWeight: 500, cursor: 'pointer', textAlign: 'center', color: 'var(--text2)', transition: 'all 0.15s' },
  statusPagoActive: { border: '1.5px solid #4ADE80', background: '#DCFCE7', color: '#15803D', fontWeight: 700 },
  statusPendenteActive: { border: '1.5px solid #FCD34D', background: '#FEF3C7', color: '#92400E', fontWeight: 700 },
  field: { display: 'flex', flexDirection: 'column', gap: 4 },
  label: { fontSize: 11, fontWeight: 600, color: 'var(--text2)' },
  input: inputBase,
  // Barra para campos nativos de data/hora: a borda/fundo ficam nesta DIV
  // (sempre 100%); o <input> nativo fica dentro, transparente. Assim a barra
  // nao encolhe mesmo quando o iOS dimensiona o campo de hora de forma estranha.
  dateBar: { ...inputBase, padding: 0, display: 'flex', alignItems: 'center', overflow: 'hidden' },
  dateInput: { border: 'none', outline: 'none', background: 'transparent', width: '100%', minWidth: 0, padding: '10px 13px', fontFamily: 'inherit', fontSize: 14, color: 'var(--text)', boxSizing: 'border-box' },
  row: { display: 'flex', gap: 10 },
  btnPrimary: btnPrimaryBase,
  btnSecondary: btnSecondaryBase,
  linkBtn: { display: 'flex', alignItems: 'center', gap: 4, fontSize: 12, color: 'var(--pink)', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 700 },
  miniForm: { background: 'var(--surface2)', borderRadius: 'var(--radius-sm)', padding: '13px', border: '1px solid var(--pink-mid)' },
}
