// Estilos da tela de Configurações (separados do componente para enxugar a lógica).
export const s = {
  page: { padding: 16, paddingBottom: 80 },
  section: { marginBottom: 24 },
  avatarUploadRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    marginBottom: 16,
    background: 'var(--surface2)',
    padding: '12px 14px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)'
  },
  avatarPreviewImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover'
  },
  avatarPlaceholder: {
    fontSize: 24,
    fontWeight: 800,
    color: 'var(--pink)',
    fontFamily: "'Bricolage Grotesque', sans-serif"
  },
  avatarInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    flex: 1
  },
  avatarTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--text)'
  },
  avatarRemoveBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--red)',
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    padding: '4px 0 0',
    alignSelf: 'flex-start',
    transition: 'opacity 0.2s'
  },
  sectionTitle: { fontSize: 11, fontWeight: 600, color: 'var(--text3)', textTransform: 'uppercase', letterSpacing: '0.6px', marginBottom: 12 },
  field: { display: 'flex', flexDirection: 'column', gap: 4, marginBottom: 12 },
  label: { fontSize: 12, fontWeight: 500, color: 'var(--text2)' },
  hint: { fontSize: 11, color: 'var(--text3)', marginTop: 2, marginBottom: 4 },
  input: { padding: '9px 12px', border: '1px solid var(--border2)', borderRadius: 'var(--radius-sm)', fontSize: 14, outline: 'none', background: 'var(--surface)', color: 'var(--text)', fontFamily: 'inherit' },
  row: { display: 'flex', gap: 10 },
  chipsRow: { display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
  chipActive: { display: 'inline-flex', alignItems: 'center', gap: 5, background: 'var(--pink-light)', color: 'var(--pink)', border: '1px solid var(--pink-mid)', borderRadius: 'var(--radius-pill)', padding: '4px 10px', fontSize: 12, fontWeight: 500 },
  chipX: { background: 'none', border: 'none', color: 'var(--pink)', cursor: 'pointer', display: 'flex', alignItems: 'center', padding: 0 },
  chipSug: { display: 'inline-flex', alignItems: 'center', background: 'var(--surface2)', color: 'var(--text2)', border: '1px solid var(--border2)', borderRadius: 'var(--radius-pill)', padding: '4px 10px', fontSize: 12, fontWeight: 500, cursor: 'pointer' },
  addRow: { display: 'flex', gap: 8, marginBottom: 8 },
  addBtn: { background: 'var(--pink)', color: 'white', border: 'none', borderRadius: 'var(--radius-sm)', padding: '0 14px', display: 'flex', alignItems: 'center', cursor: 'pointer', flexShrink: 0 },
  /* Toggle */
  toggleRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--surface2)', borderRadius: 'var(--radius-sm)', padding: '12px 14px', marginBottom: 12, cursor: 'pointer', border: '1px solid var(--border)' },
  toggleLabel: { fontSize: 13, fontWeight: 600, color: 'var(--text)', marginBottom: 2 },
  toggle: { width: 44, height: 24, borderRadius: 12, background: 'var(--border2)', position: 'relative', transition: 'background 0.2s', flexShrink: 0 },
  toggleOn: { background: 'var(--pink)' },
  toggleThumb: { position: 'absolute', top: 3, left: 3, width: 18, height: 18, borderRadius: '50%', background: 'white', transition: 'left 0.2s', boxShadow: '0 1px 4px rgba(0,0,0,0.2)' },
  toggleThumbOn: { left: 23 },
  /* Slug */
  slugRow: { display: 'flex', alignItems: 'stretch' },
  slugPrefix: { padding: '9px 10px', background: 'var(--surface2)', border: '1px solid var(--border2)', borderRadius: '8px 0 0 8px', fontSize: 13, color: 'var(--text3)', whiteSpace: 'nowrap', display: 'flex', alignItems: 'center' },
  linkPreview: { display: 'flex', alignItems: 'center', gap: 6, background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '8px 12px', marginTop: 4 },
  linkPreviewText: { flex: 1, fontSize: 12, color: 'var(--text2)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  iconBtn: { background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text2)', display: 'flex', alignItems: 'center', padding: 2, flexShrink: 0 },
  linkBtn: { display: 'flex', alignItems: 'center', gap: 4, fontSize: 11, color: 'var(--pink)', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600 },
  erro: { fontSize: 11, color: 'var(--red)', fontWeight: 500 },
  /* Dias */
  diasRow: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  diaBtn: { padding: '6px 10px', borderRadius: 'var(--radius-pill)', border: '1px solid var(--border2)', background: 'var(--surface2)', fontSize: 12, fontWeight: 500, cursor: 'pointer', color: 'var(--text2)' },
  diaBtnActive: { background: 'var(--pink)', color: 'white', border: '1px solid var(--pink)' },
  /* Save */
  btnPrimary: { width: '100%', background: 'var(--pink)', color: 'white', border: 'none', borderRadius: 'var(--radius-sm)', padding: '12px', fontSize: 14, fontWeight: 600, cursor: 'pointer', marginTop: 4, transition: 'background 0.2s' },
  btnSaved: { background: 'var(--green)' },
  divider: { height: 1, background: 'var(--border)', margin: '20px 0' },
  infoRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 0', borderBottom: '0.5px solid var(--border)' },
  infoLabel: { fontSize: 13, color: 'var(--text3)' },
  infoValue: { fontSize: 13, fontWeight: 500, color: 'var(--text)' },
  logoutBtn: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, background: 'var(--red-bg)', color: 'var(--red)', border: '0.5px solid #FFCDD2', borderRadius: 'var(--radius-sm)', padding: '11px 16px', fontSize: 14, fontWeight: 500, cursor: 'pointer', width: '100%', marginTop: 12 },
  googleCard: { display: 'flex', alignItems: 'center', gap: 12, background: 'var(--surface2)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', padding: '13px 14px' },
  googleConBtn: { background: '#4285F4', color: 'white', border: 'none', borderRadius: 8, padding: '7px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0 },
  googleDesconBtn: { background: 'var(--red-bg)', color: 'var(--red)', border: '1px solid #FFCDD2', borderRadius: 8, padding: '7px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer', whiteSpace: 'nowrap', flexShrink: 0 },
  modalDelete: { background: 'var(--surface)', borderRadius: 20, padding: '28px 24px', maxWidth: 440, width: '100%', textAlign: 'center', boxShadow: '0 24px 64px rgba(0,0,0,0.3)' },
  iconDelete: { width: 64, height: 64, borderRadius: '50%', background: 'linear-gradient(135deg, #B91C1C 0%, #DC2626 100%)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px', boxShadow: '0 8px 20px rgba(185,28,28,0.3)' },
}

export const tabs = {
  bar: {
    display: 'flex',
    gap: 4,
    background: 'var(--surface)',
    borderRadius: 'var(--radius-sm)',
    padding: 4,
    marginBottom: 20,
    boxShadow: 'var(--shadow-xs)',
    border: '1px solid var(--border)',
    overflowX: 'auto',
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
  btn: {
    flex: 1,
    minWidth: 80,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    padding: '10px 12px',
    borderRadius: 8,
    background: 'transparent',
    border: 'none',
    color: 'var(--text3)',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.15s',
    fontFamily: 'inherit',
    whiteSpace: 'nowrap',
  },
  btnAtivo: {
    background: 'var(--pink)',
    color: 'white',
    boxShadow: 'var(--shadow-pink)',
    fontWeight: 700,
  },
}
